const companyActions = {
    ADD_COMPANY_REQUEST: 'ADD_COMPANY_REQUEST',
    ADD_COMPANY_SUCCESS: 'ADD_COMPANY_SUCCESS',
    ADD_COMPANY_FAIL: 'ADD_COMPANY_FAIL',
    
    LIST_COMPANIES_REQUEST: 'LIST_COMPANIES_REQUEST',
    LIST_COMPANIES_SUCCESS: 'LIST_COMPANIES_SUCCESS',
    LIST_COMPANIES_FAIL: 'LIST_COMPANIES_FAIL'
};

export {
    companyActions
};