const userActions = {
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    
    USER_LOGOUT: 'USER_LOGOUT',
    
    USER_REGISTRATION_REQUEST: 'USER_REGISTRATION_REQUEST',
    USER_REGISTRATION_SUCCESS: 'USER_REGISTRATION_SUCCESS',
    USER_REGISTRATION_FAIL: 'USER_REGISTRATION_FAIL',

    AGENT_REGISTRATION_REQUEST: 'AGENT_REGISTRATION_REQUEST',
    AGENT_REGISTRATION_SUCCESS: 'AGENT_REGISTRATION_SUCCESS',
    AGENT_REGISTRATION_FAIL: 'AGENT_REGISTRATION_FAIL',
    AGENT_REGISTRATION_RESET: 'AGENT_REGISTRATION_RESET',

    USER_DETAILS_REQUEST: 'USER_DETAILS_REQUEST',
    USER_DETAILS_SUCCESS: 'USER_DETAILS_SUCCESS',
    USER_DETAILS_FAIL: 'USER_DETAILS_FAIL',
    USER_DETAILS_RESET: 'USER_DETAILS_RESET',
    
    USER_UPDATE_PROFILE_REQUEST: 'USER_UPDATE_PROFILE_REQUEST',
    USER_UPDATE_PROFILE_SUCCESS: 'USER_UPDATE_PROFILE_SUCCESS',
    USER_UPDATE_PROFILE_FAIL: 'USER_UPDATE_PROFILE_FAIL',
    USER_UPDATE_PROFILE_DONE: 'USER_UPDATE_PROFILE_DONE',
    
    USER_LIST_REQUEST: 'USER_LIST_REQUEST',
    USER_LIST_SUCCESS: 'USER_LIST_SUCCESS',
    USER_LIST_FAIL: 'USER_LIST_FAIL',
    USER_LIST_RESET: 'USER_LIST_RESET',

    USER_DELETE_REQUEST: 'USER_DELETE_REQUEST',
    USER_DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
    USER_DELETE_FAIL: 'USER_DELETE_FAIL',

};

const userRoles = {
    GUEST: 'GUEST',
    STAR: 'STAR',
    SUPERSTAR: 'SUPERSTAR',
    COMPANYAGENT: 'COMPANYAGENT',
    COMPANYADMIN: 'COMPANYADMIN',
    PAJ: 'PAJ',
    PAJADMIN: 'PAJADMIN'
};

export {
    userActions,
    userRoles
};