const productListActions = {
    PRODUCT_LIST_FAIL: 'PRODUCT_LIST_FAIL',
    PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST'
};

const productActions = {
    PRODUCT_DETAILS_FAIL: 'PRODUCT_DETAILS_FAIL',
    PRODUCT_DETAILS_SUCCESS: 'PRODUCT_DETAILS_SUCCESS',
    PRODUCT_DETAILS_REQUEST: 'PRODUCT_DETAILS_REQUEST'
};

export {
    productListActions,
    productActions
};