const cartActions = {
    CART_ADD_ITEM_REQUEST: 'CART_ADD_ITEM_REQUEST',
    CART_ADD_ITEM_SUCCESS: 'CART_ADD_ITEM_SUCCESS',
    CART_ADD_ITEM_FAIL: 'CART_ADD_ITEM_FAIL',
    CART_REMOVE_ITEM_REQUEST: 'CART_REMOVE_ITEM_REQUEST',
    CART_REMOVE_ITEM_SUCCESS: 'CART_REMOVE_ITEM_SUCCESS',
    CART_REMOVE_ITEM_FAIL: 'CART_REMOVE_ITEM_FAIL'
};

export {
    cartActions
};